# Generated by Django 5.0.3 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_entrymodel_cluster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='Rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
