# Generated by Django 5.0.3 on 2024-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_ratemodel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='IN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
