# Generated by Django 5.0.3 on 2024-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_entrymodel_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='IN',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
