# Generated by Django 5.0.3 on 2024-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_countmodel_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymodel',
            name='Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
