# Generated by Django 5.0.3 on 2024-08-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_partymodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemodel',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
