# Generated by Django 5.0.3 on 2024-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_ratemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
