# Generated by Django 5.0.3 on 2024-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_quotationmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTTGSTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField(blank=True, default=0, null=True)),
                ('TYPES', models.CharField(blank=True, max_length=100, null=True)),
                ('RCCode', models.CharField(blank=True, max_length=100, null=True)),
                ('RCDescription', models.TextField(blank=True, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('HSNCode', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Rate', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('Labour', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('Amount', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('GSTRate', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTAmount', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTTA', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('TotalAmount', models.CharField(blank=True, default='0', max_length=100, null=True)),
            ],
        ),
    ]
