# Generated by Django 5.0.3 on 2024-08-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_qttgstmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QTTModel',
        ),
    ]
