# Generated by Django 5.0.3 on 2024-08-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_quotationmodel_asddate_quotationmodel_asdno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='Partyid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.partymodel'),
        ),
    ]
